# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestUntitled():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):
        # Test name: Untitled
        # Step # | name | target | value
        # 1 | open | /web/login |
        list_password = [['birame.ndiaye@fongip.sn', 'ndiaye236'],
                         ['birame.ndiaye@fongip.sn', 'ndiaye36'],
                         ['birame.ndiaye@fonip.sn', 'ndiaye236'],
                         ['birame.ndiaye@fongp.sn', 'ndiaye136']]
        for i in range(len(list_password)):
            # self.driver.get("https://test-fongip.odoo.com/web/login")
            self.driver.get("http://localhost:8069/web/login")
            # 2 | setWindowSize | 1268x640 |
            self.driver.set_window_size(1268, 640)
            # 3 | click | id=login |
            time.sleep(3)
            self.driver.find_element(By.ID, "login").click()
            # 4 | type | id=login | birame.ndiaye@fongip.sn
            self.driver.find_element(By.ID, "login").send_keys(list_password[i][0])
            time.sleep(3)
            # 5 | click | id=password |
            self.driver.find_element(By.ID, "password").click()
            # 6 | type | id=password | ndiaye236
            self.driver.find_element(By.ID, "password").send_keys(list_password[i][1])
            time.sleep(3)
            # 7 | click | css=.btn-block |
            self.driver.find_element(By.CSS_SELECTOR, ".btn-block").click()




