# Generated by Selenium IDE
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select


class TestUntitled():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):
        liste_mission = [
            [1, 3, 2, "Dakar-Fatick-Dakar", "Test Automation 1", 1, 1, 2, 2, 1, 5, 5, 5, 6, 7],
            [1, 5, 2, "Dakar-Kaffrine-Dakar", "Test Automation 2", 1, 2, 4, 2, 1, 6, 6, 6, 6, 7],
            [1, 6, 2, "Dakar-Thies-Dakar", "Test Automation 3", 1, 1, 3, 2, 4, 4, 2, 4, 4, 6]
        ]
        for i in range(len(liste_mission)):
            self.driver.get(
                "http://localhost:8069/web#cids=1&menu_id=147&action=196&model=mission.delegation&view_type=form")
            self.driver.implicitly_wait(150)
            time.sleep(3)
            self.driver.find_element(By.LINK_TEXT, "Ajouter une ligne").click()
            missionnaire = Select(self.driver.find_element(By.NAME, "type_missionnaire_id"))
            missionnaire.select_by_index(liste_mission[i][0])
            time.sleep(2)
            chef = Select(self.driver.find_element(By.NAME, "chef"))
            chef.select_by_index(liste_mission[i][1])
            # self.driver.find_element(By.ID, "ui-id-9").click()
            type_mission = Select(self.driver.find_element(By.NAME, "type_mission_id"))
            type_mission.select_by_index(liste_mission[i][2])
            # self.driver.find_element(By.ID, "ui-id-16").click()
            time.sleep(2)
            self.driver.find_element(By.NAME, "trajet").click()
            self.driver.find_element(By.NAME, "trajet").send_keys(liste_mission[i][3])
            time.sleep(2)
            self.driver.find_element(By.NAME, "motif").click()
            self.driver.find_element(By.NAME, "motif").send_keys(liste_mission[i][4])
            time.sleep(2)
            moyen = Select(self.driver.find_element(By.NAME, "moyen_transport"))
            moyen.select_by_index(liste_mission[i][5])
            # self.driver.find_element(By.NAME, "moyen_transport").send_keys("Voiture")
            time.sleep(5)
            self.driver.find_element(By.NAME, "date_depart").click()
            time.sleep(2)
            self.driver.find_element(By.CSS_SELECTOR, f"tr:nth-child({liste_mission[i][11]}) > .day:nth-child({liste_mission[i][12]})").click()
            time.sleep(2)
            self.driver.find_element(By.NAME, "date_retour").click()
            time.sleep(2)
            self.driver.find_element(By.CSS_SELECTOR, f"tr:nth-child({liste_mission[i][13]}) > .day:nth-child({liste_mission[i][14]})").click()
            time.sleep(4)
            lieu_dep = Select(self.driver.find_element(By.NAME, "lieu_depart"))
            lieu_dep.select_by_index(liste_mission[i][6])
            # self.driver.find_element(By.ID, "ui-id-22").click()
            time.sleep(2)
            lieu_arr = Select(self.driver.find_element(By.NAME, "lieu_arrive"))
            lieu_arr.select_by_index(liste_mission[i][7])
            # self.driver.find_element(By.ID, "ui-id-32").click()
            time.sleep(2)
            self.driver.find_element(By.LINK_TEXT, "EQUIPE DE LA MISSION").click()
            time.sleep(2)
            self.driver.find_element(By.LINK_TEXT, "VEHICULES DE LA MISSION").click()
            self.driver.find_element(By.LINK_TEXT, "Ajouter une ligne").click()
            time.sleep(2)
            vehicle = Select(self.driver.find_element(By.NAME, "voiture_id"))
            vehicle.select_by_index(liste_mission[i][8])
            time.sleep(2)
            vehicle = Select(self.driver.find_element(By.NAME, "conducteur"))
            vehicle.select_by_index(liste_mission[i][9])
            time.sleep(2)
            self.driver.find_element(By.LINK_TEXT, "VEHICULES DE LA MISSION").click()
            time.sleep(2)
            self.driver.find_element(By.LINK_TEXT, "Ajouter une ligne").click()
            time.sleep(2)
            Select(self.driver.find_element(By.NAME, "voiture_id")).select_by_index(3)
            # vehicle.select_by_index(liste_mission[i][8])
            time.sleep(2)
            Select(self.driver.find_element(By.NAME, "conducteur")).select_by_index(3)
            # vehicle.select_by_index(liste_mission[i][9])
            time.sleep(2)
            self.driver.find_element(By.LINK_TEXT, "Carburant").click()
            carte = Select(self.driver.find_element(By.NAME, "cartecarburant_id"))
            carte.select_by_index(liste_mission[i][10])
            time.sleep(4)
            # self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_save").click()
            if i == 0:
                assert int(self.driver.find_element(By.NAME, "total_perdieme").text.replace(' ', '')) == 9 * 150000
                assert float(self.driver.find_element(By.NAME, "cout_carburant").text.replace(' ', '').replace(',', '.')) == 39 * 990
                assert int(self.driver.find_element(By.NAME, "cout_mission").text.replace(' ', '')) == 1350000 + (39 * 990)
            elif i == 1:
                assert int(self.driver.find_element(By.NAME, "total_perdieme").text.replace(' ', '')) == 1 * 150000
                assert float(self.driver.find_element(By.NAME, "cout_carburant").text.replace(' ', '').replace(',', '.')) == 60 * 990
                assert int(self.driver.find_element(By.NAME, "cout_mission").text.replace(' ', '')) == 150000 + (
                            60 * 990)
            elif i == 2:
                assert int(self.driver.find_element(By.NAME, "total_perdieme").text.replace(' ', '')) == 16 * 150000
                assert float(self.driver.find_element(By.NAME, "cout_carburant").text.replace(' ', '').replace(',', '.')) == 27.60 * 990
                assert int(self.driver.find_element(By.NAME, "cout_mission").text.replace(' ', '')) == 16 * 150000 + (
                        27.60 * 990)
