# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestUntitled():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):
        liste_adresse = [["Saint-Louis", "235"], ["Louga", "200"], ["Matam", "350"]]
        for i in range(len(liste_adresse)):
            self.driver.get("https://test-fongip.odoo.com/web#menu_id=439&cids=1&action=634&model=mission.adresse"
                            "&view_type=form")
            self.driver.implicitly_wait(150)
            time.sleep(3)
            self.driver.find_element(By.NAME, "nom_ville").click()
            self.driver.find_element(By.NAME, "nom_ville").send_keys(liste_adresse[i][0])
            time.sleep(2)
            self.driver.find_element(By.NAME, "distance").click()
            self.driver.find_element(By.NAME, "distance").send_keys(liste_adresse[i][1])
            time.sleep(2)
            self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_save").click()
            time.sleep(3)
            # self.driver.find_element(By.CSS_SELECTOR, ".o_form_button_create").click()
